-- SQLite
INSERT INTO Question_cards (id, answer)
VALUES
("bc_index=0,card_sets=[2]","Here is the church Here is the steeple Open the doors And there is ____."),
("bc_index=1,card_sets=[2,103,134,166]","50% of all marriages end in ____."),
("bc_index=2,card_sets=[2]","As the mom of five rambunctious boys, I'm no stranger to ____."),
("bc_index=3,card_sets=[2,103,134,166,191]","Next from J.K. Rowling: <i>Harry Potter and the Chamber of ____.</i>"),
("bc_index=4,card_sets=[2,103,134,166]","This is the way the world ends This is the way the world ends Not with a bang but with ____."),
("bc_index=5,card_sets=[2,103,134,166]","After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ____."),
("bc_index=6,card_sets=[2,103,134,166]","When Pharaoh remained unmoved, Moses called down a Plague of ____."),
("bc_index=7,card_sets=[2,103,134,191]","What's there a ton of in heaven?"),
("bc_index=8,card_sets=[2,103,134,166,191]","It's a pity that kids these days are all getting involved with ____."),
("bc_index=9,card_sets=[2,103,134,166,191]","What's a girl's best friend?"),
("bc_index=10,card_sets=[2,103,166]","____. High five, bro."),
("bc_index=13,card_sets=[2,103,191]","The class field trip was completely ruined by ____."),
("bc_index=14,card_sets=[2,103,134,166]","If you can't be with the one you love, love ____."),
("bc_index=15,card_sets=[2]","When I am a billionaire, I shall erect a 50-foot statue to commemorate ____."),
("bc_index=16,card_sets=[2,103,166]","I'm LeBron James, and when I'm not slamming dunks, I love ____."),
("bc_index=17,card_sets=[2,103,134,166,191]","Uh, hey guys, I know this was my idea, but I'm having serious doubts about ____."),
("bc_index=18,card_sets=[2,103,134,166]","Alternative medicine is now embracing the curative powers of ____."),
("bc_index=20,card_sets=[2,103,191]","I'm sorry, Professor, but I couldn't complete my homework because of ____."),
("bc_index=21,card_sets=[2,103,134,166,191]","I drink to forget ____."),
("bc_index=22,card_sets=[2]","Next on ESPN2: The World Series of ____."),
("bc_index=23,card_sets=[2,103,134,166,191]","Hey Reddit! I'm ____. Ask me anything."),
("bc_index=25,card_sets=[2,103,134,166]","How did I lose my virginity?"),
("bc_index=26,card_sets=[2,103,134,166]","I'm going on a cleanse this week. Nothing but kale juice and ____."),
("bc_index=27,card_sets=[2]","Dear Abby, I'm having some trouble with ____ and would like your advice."),
("bc_index=28,card_sets=[2,103,134,166]","____. That was so metal."),
("bc_index=29,card_sets=[2,103,134,166,191]","I got 99 problems but ____ ain't one."),
("bc_index=30,card_sets=[2,103,134,166,191]","Why can't I sleep at night?"),
("bc_index=31,card_sets=[2,191]","Dude, <i>do not</i> go in that bathroom. There's ____ in there."),
("bc_index=33,card_sets=[2]","Hey guys, welcome to Chili's! Would you like to start the night off right with ____?"),
("bc_index=34,card_sets=[2,191]","Just once, I'd like to hear you say ""Thanks, Mom. Thanks for ____."""),
("bc_index=35,card_sets=[2]","Old Macdonald had ____. E-I-E-I-O."),
("bc_index=36,card_sets=[2,103,134,166,191]","What made my first kiss so awkward?"),
("bc_index=37,card_sets=[2,191]","Just saw this upsetting video! Please retweet!! #stop____"),
("bc_index=38,card_sets=[2,103,134,166,191]","What never fails to liven up the party?"),
("bc_index=39,card_sets=[2,103,134,166]","Kids, I don't need drugs to get high. I'm high on ____."),
("bc_index=41,card_sets=[2,103,134]","Life for American Indians was forever changed when the White Man introduced them to ____."),
("bc_index=42,card_sets=[2]","Men's Wearhouse. You're gonna like ____. I guarantee it."),
("bc_index=43,card_sets=[2,103,166]","____. Betcha can't have just one!"),
("bc_index=44,card_sets=[2,103,166]","Instead of coal, Santa now gives the bad children ____."),
("bc_index=45,card_sets=[2]","The Chevy Tahoe. With the power and space to take ____ everywhere you go."),
("bc_index=46,card_sets=[2]","Click here for ____!!!"),
("bc_index=47,card_sets=[2]","TSA guidelines now prohibit ____ on airplanes."),
("bc_index=48,card_sets=[2,103,134,166,191]","What would grandma find disturbing, yet oddly charming?"),
("bc_index=49,card_sets=[2,103,134,166,191]","What's that sound?"),
("bc_index=50,card_sets=[2]","What is Batman's guilty pleasure."),
("bc_index=51,card_sets=[2]","After eight years in the White House, how is Obama finally letting loose?"),
("bc_index=52,card_sets=[2]","This season at Steppenwolf, Samuel Beckett's classic existential play: Waiting for ____."),
("bc_index=53,card_sets=[2]","A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ____."),
("bc_index=55,card_sets=[2]","Mabe she's born with it. Maybe it's ____."),
("bc_index=57,card_sets=[2]","Arby's: We Have ____."),
("bc_index=58,card_sets=[2,103,134,166,191]","What will always get you laid?"),
("bc_index=59,card_sets=[2,103]","My fellow Americans: Before this decade is out, we <i>will</i> have ____ on the moon!"),
("bc_index=60,card_sets=[2,103,134,166,191]","What ended my last relationship?"),
("bc_index=61,card_sets=[2,103,134,166,191]","Why do I hurt all over?"),
("bc_index=62,card_sets=[2]","When I am President, I will create the Department of ____."),
("bc_index=63,card_sets=[2,191]","But before I kill you, Mr. Bond, I must show you ____."),
("bc_index=65,card_sets=[2]","What's Teach For America using to inspire inner city students to succeed?"),
("bc_index=66,card_sets=[2,103,134,166,191]","War! What is it good for?"),
("bc_index=68,card_sets=[2,103,134,166]","Military historians remember Alexander the Great for his brilliant use of ____ against the Persians."),
("bc_index=69,card_sets=[2,166,191]","A romantic, candlelit dinner would be incomplete without ____."),
("bc_index=70,card_sets=[2,166,191]","Coming to Broadway this season, ____: The Musical."),
("bc_index=71,card_sets=[2]","Brought to you by Bud Light&reg;, the official Beer of ____."),
("bc_index=72,card_sets=[2,103,134,166]","Check me out, yo! I call this dance move ""____."""),
("bc_index=74,card_sets=[2,103]","Introducing X-treme Baseball! It's like baseball, but with ____!"),
("bc_index=75,card_sets=[2,103,134,166,191]","Fun tip! When your man asks you to go down on him, try surprising him with ____ instead."),
("bc_index=76,card_sets=[2]","I'm no doctor but I'm pretty sure what you're suffering from is called ""____."""),
("bc_index=77,card_sets=[2]","Bravo's new reality show features eight washed-up celebrities living with ____."),
("bc_index=78,card_sets=[2,103,134,166]","White people like ____."),
("bc_index=79,card_sets=[2,103,134,166]","____: kid-tested, mother-approved."),
("bc_index=80,card_sets=[2,103]","IF you like ____, YOU MIGHT BE A REDNECK."),
("bc_index=81,card_sets=[2,103,134,166,191]","What gives me uncontrollable gas?"),
("bc_index=83,card_sets=[2,103]","Today on <i>Maury</i> : ""Help! My son is ____!"""),
("bc_index=84,card_sets=[2,103,134,166]","What is George W. Bush thinking about right now?"),
("bc_index=86,card_sets=[2,103,134,166,191]","What's that smell?"),
("bc_index=87,card_sets=[2,103,134,166,191]","____. It's a trap!"),
("bc_index=88,card_sets=[2,103,134,166,191]","Well if you'll excuse me, gentlemen, I have a date with ____."),
("bc_index=89,card_sets=[2,103,134]","&#x2605;&#x2606;&#x2606;&#x2606;&#x2606; Do NOT go here! Found ____ in my Kung Pao chicken!"),
("bc_index=90,card_sets=[2,103,134,166,191]","Why am I sticky?"),
("bc_index=91,card_sets=[2,103,134,166,191]","What makes life worth living?"),
("bc_index=92,card_sets=[2]","In the Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time."),
("bc_index=93,card_sets=[2,103]","While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____."),
("bc_index=94,card_sets=[2,103,134,166,191]","What's my secret power?"),
("bc_index=95,card_sets=[2,103,134,166,191]","What are my parents hiding from me?"),
("bc_index=96,card_sets=[2,103,191]","Daddy, why is mommy crying?"),
("bc_index=97,card_sets=[2,103,134,166,191]","During sex, I like to think about ____."),
("bc_index=98,card_sets=[2,103,134,166,191]","Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ____?"),
("bc_index=99,card_sets=[2,103,134,166]","I get by with a little help from ____."),
("bc_index=100,card_sets=[103,134,166,191]","I'm no doctor, but I'm pretty sure what you're suffering from is called ""____."""),
("bc_index=101,card_sets=[103]","As the mom of five rambunctious boys, I'm not stranger to ____."),
("bc_index=103,card_sets=[103]","Just once I'd like to hear you say ""Thanks, Mom. Thanks for ____."""),
("bc_index=104,card_sets=[103]","Bravo's new reality show feature eight washed-up celebrities living with ____."),
("bc_index=105,card_sets=[103]","Air Canada guidelines now prohibit ____ on airplanes."),
("bc_index=106,card_sets=[103]","When I am Prime Minister of Canada, I will create the Ministry of ____."),
("bc_index=107,card_sets=[103]","Coming to Broadway this season, ____; The Musical."),
("bc_index=108,card_sets=[103]","This season at the Princess of Wales Theatre, Samuel Beckett's classic existential play: <i>Waiting for ____.</i>"),
("bc_index=109,card_sets=[103,134,166]","Here is church Here is the steeple Open the doors And there is ____."),
("bc_index=110,card_sets=[103]","Penalty! ____: that's 5 minutes in the box!"),
("bc_index=111,card_sets=[103,134,166,191]","Click Here for ____!!!"),
("bc_index=112,card_sets=[103]","Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ____?"),
("bc_index=113,card_sets=[103]","I know when that hotline bling, that can only mean one thing: ____."),
("bc_index=114,card_sets=[103]","Dude, <i>do not</i> go in that washroom. There's ____ in there."),
("bc_index=115,card_sets=[103,134,166]","Just saw this upsetting video! Please retweet!! #stop ____"),
("bc_index=116,card_sets=[103]","Brought to you by Molson Canadian, the Official Beer of ____."),
("bc_index=117,card_sets=[103,134,166]","Maybe she's born with it. Maybe it's ____."),
("bc_index=118,card_sets=[103]","Next on TSN: The World Series of ____."),
("bc_index=119,card_sets=[103,134]","A romantic, candlelit dinner would be incomplete without  ____."),
("bc_index=120,card_sets=[103]","O Canada, we stand on guard for ____."),
("bc_index=121,card_sets=[103,134,166,191]","What is Batman's guilty pleasure?"),
("bc_index=122,card_sets=[103,134,166]","Old MacDonald has ____. E-I-E-I-O."),
("bc_index=123,card_sets=[103,134,166]","A recent laboratory study shows that undergraduates have 50% less sex after being exposed to: ____."),
("bc_index=124,card_sets=[103]","Dear Abby, I'm having some trouble ____ and would like your advice."),
("bc_index=125,card_sets=[103,166]","In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time."),
("bc_index=126,card_sets=[103]","Skidamarink a dink a dink, skidamarink a doo, I love ____."),
("bc_index=127,card_sets=[103,134,166]","But before I kill you, Mr. Bond, I must show you."),
("bc_index=128,card_sets=[103]","The new Chevy Tahoe. With the power and space to take ____ everywhere you go."),
("bc_index=129,card_sets=[103,134,166]","When I am a billionaire, I shall erect a 20-metre statue to commemorate ____."),
("bc_index=130,card_sets=[134]","Airport security guidelines now prohibit ____ on airplanes."),
("bc_index=131,card_sets=[134]","____? Jim'll fix it!"),
("bc_index=132,card_sets=[134,166]","Daddy, why is mummy crying?"),
("bc_index=133,card_sets=[134]","Today on <i>The Jeremy Kyle Show:</i> ""Help! My son is ____!"""),
("bc_index=134,card_sets=[134]","What did I bring back from Amsterdam?"),
("bc_index=135,card_sets=[134]","Mate, <i>do not go</i> in that bathroom. There's ____ in there."),
("bc_index=136,card_sets=[134]","____. Once you pop, the fun don't stop!"),
("bc_index=137,card_sets=[134]","When I am Prime Minister of the United Kingdom, I will create the Ministry of ____."),
("bc_index=138,card_sets=[134]","Instead of coal, Father Christmas now gives the bad children ____."),
("bc_index=139,card_sets=[134,166]","Just once I'd like to hear you say ""Thanks, Mum. Thanks for ____."""),
("bc_index=140,card_sets=[134]","UKIP: Putting ____ First!"),
("bc_index=142,card_sets=[134]","TFL apologizes for the delay in train service due to ____."),
("bc_index=143,card_sets=[134]","Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ____."),
("bc_index=144,card_sets=[134]","The school trip was completely ruined by ____."),
("bc_index=145,card_sets=[134,166]","How am I maintaining my relationship status?"),
("bc_index=146,card_sets=[134,166]","As the mum of five rambunctious boys, I'm not stranger to ____."),
("bc_index=147,card_sets=[134]","Next on Sky Sports: The World Champion of ____.."),
("bc_index=148,card_sets=[134]","What's the next Happy Meal&reg; toy?"),
("bc_index=149,card_sets=[134,191]","The theme for next year's Eurovision Song Contest is ""We are ____."""),
("bc_index=150,card_sets=[134]","Next up on Channel 4: Ramsay's ____ Nightmares."),
("bc_index=151,card_sets=[134]","In Belmarsh Prison, word is you can trade 200 cigarettes for ____."),
("bc_index=152,card_sets=[134]","Now at the Natural History Museum: an interactive exhibit on ____."),
("bc_index=153,card_sets=[134]","Hey guys, welcome to TGIF! Would you like to start the night off right with ____?"),
("bc_index=154,card_sets=[134]","Coming to the West End this year, ____: The Musical."),
("bc_index=156,card_sets=[134]","This season at the Old Vic, Samuel Beckett's classic existential play: Waiting for ____."),
("bc_index=157,card_sets=[134]","Channel 5's new reality show feature eight washed-up celebrities living with ____."),
("bc_index=158,card_sets=[134,166]","I'm sorry, Sir, but I couldn't complete my homework because of ____."),
("bc_index=159,card_sets=[134]","____. That's what mums go to Iceland."),
("bc_index=161,card_sets=[134]","Dear Agony Aunt, I'm having some trouble with ____ and would like your advice."),
("bc_index=162,card_sets=[166]","Oi! Show us ____!"),
("bc_index=163,card_sets=[166]","What did I bring back from Bali?"),
("bc_index=164,card_sets=[166]","MTV's new reality show features eight washed-up celebrities living with ____."),
("bc_index=165,card_sets=[166]","&#x2605;&#x2606;&#x2606;&#x2606;&#x2606; Do NOT go here! Found ____ in my Mongolian chicken!"),
("bc_index=166,card_sets=[166]","What broke up the original Wiggles?"),
("bc_index=167,card_sets=[166]","Today on <i>Jerry Springer:</i> ""Help! My son is ____!"""),
("bc_index=168,card_sets=[166]","This season at the Sydney Opera House, Samuel Beckett's classic existential play: <i>Waiting for ____.</i>"),
("bc_index=169,card_sets=[166]","Crikey! I've never seen ____ like this before! Let's get a bit closer."),
("bc_index=170,card_sets=[166]","What's there a tonne of in heaven?"),
("bc_index=171,card_sets=[166]","What makes me a true blue Aussie?"),
("bc_index=172,card_sets=[166]","The school excursion was completely ruined by ____."),
("bc_index=173,card_sets=[166]","Channel 9 is pleased to present its new variety show, ""Hey Hey It's ____."""),
("bc_index=174,card_sets=[166]","Qantas now prohibits ____ on airplanes."),
("bc_index=176,card_sets=[166]","Next on Nine's Wide World of Sports: The World Series of ____."),
("bc_index=177,card_sets=[166]","Are you thinking what I'm thinking, B1? I think I am, B2: it's ____ time!"),
("bc_index=178,card_sets=[166]","____? Yeah, nah."),
("bc_index=179,card_sets=[166]","Life for Aboriginal people was forever changed when the white man introduced them to ____."),
("bc_index=180,card_sets=[166]","Hey guys, welcome to Sizzler! Would you like to start the night off right with ____?"),
("bc_index=181,card_sets=[166]","Brought to you by XXXX Gold, the Official Beer of ____."),
("bc_index=182,card_sets=[166]","Mate, <i>do not</i> go in that toilet. There's ____ in there."),
("bc_index=183,card_sets=[166]","In Australia, ____ is twice as big and twice as deadly."),
("bc_index=184,card_sets=[166]","When I am Prime Minister, I will create the Department of ____."),
("bc_index=185,card_sets=[191,235]","What brought the orgy to a grinding halt?"),
("bc_index=186,card_sets=[191,235]","Lovin' you is easy 'cause you're ____."),
("bc_index=187,card_sets=[191]","Your persistence is admirable, my dear Prince. But you cannot win my heart with ____ alone."),
("bc_index=188,card_sets=[191]","The blind date was going horrible until we discovered our shared interest in ____."),
("bc_index=189,card_sets=[191,235]","Science will never explain ____."),
("bc_index=190,card_sets=[191,235]","The Five Stages of Grief: denial, anger, bargaining, ____, acceptance."),
("bc_index=191,card_sets=[191,235]","What has been making life difficult at the nudist colony?"),
("bc_index=192,card_sets=[191,235]","Charades was ruined for me forever when my mom had to act out ____."),
("bc_index=193,card_sets=[191,235]","Money can't buy me love, but it can buy me ____."),
("bc_index=194,card_sets=[191,235]","During his midlife crisis, my dad got really into ____."),
("bc_index=196,card_sets=[191,235]","This is your captain speaking. Fasten your seatbelts and prepare for ____."),
("bc_index=197,card_sets=[191]","Tonight's top story: What you don't know about ____ could kills you."),
("bc_index=198,card_sets=[191,235]","Future historians will agree that ____ marked the beginning of America's decline."),
("bc_index=199,card_sets=[191]","Coming this season, Samuel Beckett's classic existential play: <i>Waiting for ____.</i>"),
("bc_index=200,card_sets=[191,235]","When I pooped, what came out of my butt?"),
("bc_index=201,card_sets=[191,235]","A successful job interview begins with a firm handshake and ends with ____."),
("bc_index=202,card_sets=[191,235]","Finally! A service that delivers ____ right to your door."),
("bc_index=203,card_sets=[191,235]","And what did <i>you</i> bring for show and tell?"),
("bc_index=204,card_sets=[191]","When I am a billionaire, I shall erect a 20-meter statue to commemorate ____."),
("bc_index=205,card_sets=[191,235]","When all else fails, I can always masturbate to ____."),
("bc_index=208,card_sets=[191]","Next on Eurosport: The World Championship of ____."),
("bc_index=209,card_sets=[191,235]","In his new self-produced album, Kanye West raps over the sounds of ____."),
("bc_index=210,card_sets=[191,235]","In Rome, there are whisperings that the Vatican has a secret room devoted to ____."),
("bc_index=212,card_sets=[191,235]","The secret to a lasting marriage is communication, communication, and ____."),
("bc_index=214,card_sets=[191,235]","In the seventh circle of Hell, sinners must endure ____ for all eternity."),
("bc_index=215,card_sets=[191,235]","____. Awesome in theory, kind of a mess in practice."),
("bc_index=216,card_sets=[191,235]","My plan for world domination begins with ____."),
("bc_index=217,card_sets=[191,235]","I learned the hard way that you can't cheer up a grieving friend with ____."),
("bc_index=218,card_sets=[191,235]","A remarkable new study shows that chimps have evolved their own primitive version of ____."),
("bc_index=220,card_sets=[191]","When I am Prime Minister, I will create the Ministry of ____."),
("bc_index=221,card_sets=[191,235]","Turns out that ____-Man was neither the hero we needed nor wanted."),
("bc_index=223,card_sets=[191,235]","What left this stain on my couch?"),
("bc_index=225,card_sets=[191,235]","I'm not like the rest of you. I'm too rich and busy for ____."),
("bc_index=226,card_sets=[191,235]","The healing process began when I joined a support group for victims of ____."),
("bc_index=227,card_sets=[191,235]","Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ____!"),
("bc_index=228,card_sets=[191,235]","Only two things in life are certain: death and ____."),
("bc_index=229,card_sets=[235]","This month's Cosmo: ""Spice up your sex life by bringing ____ into the bedroom."""),
("bc_index=230,card_sets=[235]","Next time on Dr. Phil: How to talk to your child about ____."),
("bc_index=231,card_sets=[235]","Tonight on 20/20: What you don't know about ____ could kill you."),
("bc_index=232,card_sets=[235]","My new favorite porn star is Joey ""____"" McGee."),
("bc_index=236,card_sets=[235]","Aww, sick! I just saw this skater do a 720 kickflip into ____!"),
("bc_index=237,card_sets=[235]","What's harshing my mellow, man?"),
("bc_index=238,card_sets=[235]","I love being a mom. But it's tough when my kids come home filthy from ____. That's why there's Tide&reg;."),
("bc_index=239,card_sets=[235]","As part of his daily regimen, Anderson Cooper sets aside 15 minutes for ____."),
("bc_index=240,card_sets=[235]","To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of ____."),
("bc_index=241,card_sets=[235]","Welcome to Se&ntilde;or Frog's! Would you like to try our signature cocktail, ""____ on the Beach""?"),
("bc_index=242,card_sets=[235]","Hey baby, come back to my place and I'll show you ____."),
("bc_index=244,card_sets=[235]","Your persistence is admirable, my dear Prince, But you cannot win my heart with ____ alone."),
("bc_index=246,card_sets=[235]","During high school, I never really fit in until I found ____ club."),
("bc_index=247,card_sets=[235]","Little Miss Muffet<br>Sat on a tuffet,<br>Eating her curds<br>and ____."),
("bc_index=248,card_sets=[235]","In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated ____."),
("bc_index=249,card_sets=[235]","My gym teacher got fired for adding ____ to the obstacle course."),
("bc_index=250,card_sets=[235]","The blind date was going horribly until we discovered our shared interest in ____."),
("bc_index=251,card_sets=[235]","My country, 'tis of thee, sweet land of ____."),
("bc_index=252,card_sets=[235]","Call the law offices of Goldstein &amp; Goldstein, because no one should have to tolerate ____ in the workplace."),
("bc_index=253,card_sets=[235]","Members of New York's social elite are paying thousands of dollars just to experience ____."),
("bc_index=254,card_sets=[235]","In his newest and most difficult stunt, David Blaine must escape from ____."),
("bc_index=258,card_sets=[235]","Next week on the Discovery Channel, one man must survive in the depths of the Amazon with only ____ and his wits."),
("bc_index=261,card_sets=[235]","And I would have gotten away with it, too, if it hadn't been for ____!"),
("bc_index=262,card_sets=[235]","Legend has it Prince wouldn't perform without ____ in his dressing room."),
("bc_index=263,card_sets=[271]","Dear Leader Kim Jong-un, our village praises your infinite wisdom with a humble offering of ____."),
("bc_index=265,card_sets=[271]","Do <i>not</i> fuck with me! I am literally ____ right now."),
("bc_index=266,card_sets=[271]","And would you like those buffalo wings mild, hot, or ____?"),
("bc_index=267,card_sets=[271]","What's fun until it gets weird?"),
("bc_index=268,card_sets=[271]","And today's soup is Cream of ____."),
("bc_index=269,card_sets=[271]","Come to Dubai, where you can relax in our world-famous spas, experience the nightlife, or simply enjoy ____ by the poolside."),
("bc_index=270,card_sets=[271]","She's up all night for good fun. I'm up all night for ____."),
("bc_index=271,card_sets=[271]","Hi MTV! My name is Kendra, I live in Malibu, I'm into ____, and I love to have a good time."),
("bc_index=277,card_sets=[271]","""This is madness!""<br><br> <i>No.</i> THIS IS ____!"),
("bc_index=278,card_sets=[271]","It lurks in the night. It hungers for flesh. This summer, no one is safe from ____."),
("bc_index=280,card_sets=[271]","I don't mean to brag, but they call me the Michael Jordan of ____."),
("bc_index=281,card_sets=[271]","Don't forget! Beginning this week, Casual Friday will officially become ""____ Friday."""),
("bc_index=282,card_sets=[271]","Having the worst day EVER. #____"),
("bc_index=283,card_sets=[271]","Why am I broke?"),
("bc_index=284,card_sets=[271]","Wes Anderson's new film tells the story of a precocious child coming to terms with ____."),
("bc_index=287,card_sets=[271]","Yo' mama so fat she ____!"),
("bc_index=288,card_sets=[271]","Now in bookstores: ""The Audacity of ____,"" by Barack Obama."),
("bc_index=289,card_sets=[271]","In his new action comedy, Jackie Chan must fend off ninjas while also dealing with ____."),
("bc_index=290,card_sets=[271]","Armani suit: $1,000. Dinner for two at that swanky restaurant: $300. The look on her face when you surprise her with ____: priceless."),
("bc_index=291,card_sets=[271]","Behind every powerful man is ____."),
("bc_index=292,card_sets=[271]","Life's pretty tough in the fast lane. That's why I never leave the house without ____."),
("bc_index=293,card_sets=[271]","You are not alone. Millions of Americans struggle with ____ every day."),
("bc_index=294,card_sets=[271]","My grandfather worked his way up from nothing. When he came to this country, all he had was the shoes on his feet and ____."),
("bc_index=296,card_sets=[271]","Man, this is bullshit. Fuck ____."),
("bc_index=298,card_sets=[271]","The Japanese have developed a smaller, more efficient version of ____."),
("bc_index=299,card_sets=[271]","Do you lack energy? Does it sometimes feel like the whole world is ____? Ask your doctor about Zoloft&reg;."),
("bc_index=300,card_sets=[271]","I work my ass off all day for this family, and this is what I come home to? ____!?"),
("bc_index=301,card_sets=[271]","This is America. If you don't work hard, you don't succeed. I don't care if you're black, white, purple, or ____."),
("bc_index=302,card_sets=[271]","Dammit, Gary. You can't just solve every problem with ____."),
("bc_index=303,card_sets=[271]","James is a lonely boy. But when he discovers a secret door in his attic, he meets a magical new friend: ____."),
("bc_index=304,card_sets=[271]","This is the prime of my life. I'm young, hot, and full of ____."),
("bc_index=307,card_sets=[271]","WHOOO! God <i>damn</i> I love ____!"),
("bc_index=308,card_sets=[271]","You Won't Believe These 15 Hilarious ____ Bloopers!"),
("bc_index=309,card_sets=[271]","You've seen the bearded lady! You've seen the ring of fire! Now, ladies and gentlemen, feast your eyes upon ____!"),
("bc_index=310,card_sets=[271]","When I was a kid, we used to play Cowboys and ____."),
("bc_index=311,card_sets=[271]","Do the Dew&reg; with our most extreme flavor yet! Get ready for Mountain Dew ____!"),
("bc_index=314,card_sets=[271]","What's making things awkward in the sauna?"),
("bc_index=315,card_sets=[271]","Listen, Gary, I like you. But if you want that corner office, you're going to have to show me ____."),
("bc_index=316,card_sets=[271]","Help me doctor, I've got ____ in my butt."),
("bc_index=319,card_sets=[271]","In his farewell address, George Washington famously warned Americans about the dangers of ____."),
("bc_index=320,card_sets=[271]","Well what do you have to say for yourself, Casey? This is the third time you've been sent to the principal's office for ____."),
("bc_index=321,card_sets=[271]","Here at the Academy for Gifted Children, we allow students to explore ____ at their own pace."),
("bc_index=322,card_sets=[271]","Get ready for the movie of the summer! One cop plays by the book. The other's only interested in one thing: ____."),
("bc_index=324,card_sets=[271]","As king, how will I keep the peasants in line?"),
("bc_index=325,card_sets=[271]","I'm sorry, sir, but we don't allow ____ at the country club."),
("bc_index=326,card_sets=[271]","2 AM in the city that never sleeps. The door swings open and <i>she</i> walks in, legs up to here. Something in her eyes tells me she's looking for ____."),
("bc_index=327,card_sets=[271]","I have a strict policy. First date, dinner. Second date, kiss. Third date, ____."),
("bc_index=328,card_sets=[271]","What killed my boner?"),
("bc_index=329,card_sets=[271]","Hi, this is Jim from accounting. We noticed a $1,200 charge labeled ""____."" Can you explain?"),
("bc_index=330,card_sets=[271]","I'm pretty sure I'm high right now, because I'm absolutely mesmerized by ____."),
("bc_index=331,card_sets=[271]","Don't worry, kid. It gets better. I've been living with ____ for 20 years."),
("bc_index=332,card_sets=[271]","How am I compensating for my tiny penis?"),
("bc_index=333,card_sets=[342]","Ooo, daddy like ____."),
("bc_index=334,card_sets=[342,414]","As reparations for slavery, all African Americans will receive ____."),
("bc_index=335,card_sets=[342]","What's about to take this dance floor to the next level?"),
("bc_index=336,card_sets=[342]","What are all those whales singing about?"),
("bc_index=337,card_sets=[342]","I've got rhythm, I've got music, I've got ____. Who could ask for anything more?"),
("bc_index=338,card_sets=[342]","Then the princess kissed the frog, and all of a sudden the frog was ____!"),
("bc_index=339,card_sets=[342]","What turned me into a Republican?"),
("bc_index=340,card_sets=[342]","If at first you don't succeed, try ____."),
("bc_index=341,card_sets=[342]","Poor Brandon, still living in his parents' basement. I hear he never got over ____."),
("bc_index=342,card_sets=[342]","Coming to Red Lobster&reg; this month, ____."),
("bc_index=343,card_sets=[342]","Most Americans would not vote for a candidate who is openly ____."),
("bc_index=344,card_sets=[342]","This Friday at the Liquid Lounge, it's ____ Night! Ladies drink free."),
("bc_index=345,card_sets=[342]","Well, shit. My eyes ain't so good, but I'll eat my own boot if that ain't ____!"),
("bc_index=346,card_sets=[342]","CNN breaking news! Scientists discover ____."),
("bc_index=347,card_sets=[342]","She's a lady in the streets, ____ in the sheets."),
("bc_index=348,card_sets=[342]","There is no God. It's just ____ and then you die."),
("bc_index=349,card_sets=[342]","Best you go back where you came from, now. We don't take too kindly to ____ in these parts."),
("bc_index=350,card_sets=[342]","I've had a horrible vision, father. I saw mountains crumbling, stars falling from the sky. I saw ____."),
("bc_index=351,card_sets=[342]","Oh no! Siri, how do I fix ____?"),
("bc_index=352,card_sets=[342]","Girls just wanna have ____."),
("bc_index=353,card_sets=[342]","What's the gayest?"),
("bc_index=354,card_sets=[342]","Son, take it from someone who's been around the block a few times. Nothin' puts her in the mood like ____."),
("bc_index=355,card_sets=[342]","Mom's to-do list:<br><br>Buy groceries<br>Clean up ____<br>Soccer practice"),
("bc_index=356,card_sets=[342]","What will end racism once and for all?"),
("bc_index=357,card_sets=[342]","No, no, no, no, no, NO! I will NOT let ____ ruin this wedding."),
("bc_index=358,card_sets=[342]","Summer lovin', had me a blast. ____, happened so fast."),
("bc_index=359,card_sets=[342]","I'm sorry, sir, but your insurance plan doesn't cover injuries caused by ____."),
("bc_index=360,card_sets=[342]","What sucks balls?"),
("bc_index=361,card_sets=[342]","Errbody in the club ____."),
("bc_index=362,card_sets=[342]","I'll take the BBQ bacon burger with a fried egg and fuck it how about ____."),
("bc_index=363,card_sets=[342]","You won't believe what's in my pussy. It's ____."),
("bc_index=364,card_sets=[342]","The top Google auto-complete results for Barack Obama: <br>Barack Obama height.<br>Barack Obama net worth.<br>Barack Obama ____."),
("bc_index=365,card_sets=[342]","I may not be much to look at, but I fuck like ____."),
("bc_index=366,card_sets=[342]","LSD + ____ = really bad time."),
("bc_index=367,card_sets=[342]","Feeling so grateful! #amazing #mylife #____"),
("bc_index=368,card_sets=[342]","Art isn't just a painting in a stuffy museum. Art is alive. Art is ____."),
("bc_index=369,card_sets=[342]","Why am I laughing and crying and taking off my clothes?"),
("bc_index=370,card_sets=[342]","Google Calendar alert: ____ in 10 minutes."),
("bc_index=371,card_sets=[342]","One more thing. Watch out for Big Mike. They say he killed a man with ____."),
("bc_index=372,card_sets=[342]","Dance like there's nobody watching, love like you'll never be hurt, and live like you're ____."),
("bc_index=374,card_sets=[342]","In the 1950s, psychologists prescribed ____ as a cure for homosexuality."),
("bc_index=375,card_sets=[342]","Well if ____ is a crime, then lock me up!"),
("bc_index=376,card_sets=[342]","Run, run, as fast as you can! You can't catch me, I'm ____!"),
("bc_index=377,card_sets=[342]","What's the most problematic?"),
("bc_index=378,card_sets=[342]","With a one-time gift of just $10, you can save this child from ____."),
("bc_index=380,card_sets=[342]","You know who else liked ____? Hitler."),
("bc_index=381,card_sets=[342]","What totally destroyed my asshole?"),
("bc_index=382,card_sets=[342]","I don't believe in God. I believe in ____."),
("bc_index=383,card_sets=[342]","She's just one of the guys, you know? She likes beer, and football, and ____."),
("bc_index=384,card_sets=[342]","Congratulations! You have been selected for our summer internship program. While we are unable to offer a salary, we <i>can</i> offer you ____."),
("bc_index=385,card_sets=[342]","I tell you, it was a non-stop fuckfest. When it was over, my asshole looked like ____."),
("bc_index=386,card_sets=[342]","We do not shake with our left hands in this country. That is the hand we use for ____."),
("bc_index=387,card_sets=[342]","As Teddy Roosevelt said, the four manly virtues are honor, temperance, industry, and ____."),
("bc_index=388,card_sets=[398]","How did Stella get her groove back?"),
("bc_index=389,card_sets=[398]","Siskel and Ebert have panned ____ as poorly conceived and sloppily executed."),
("bc_index=390,card_sets=[398]","Up next on Nickelodeon: Clarissa Explains ____."),
("bc_index=391,card_sets=[398]","It''s Morphin' Time! Mastodon! Pterodactyl! Triceratops! Sabertooth Tiger! ____!"),
("bc_index=392,card_sets=[398]","Believe it or not, Jim Carrey can do a dead-on impression of ____."),
("bc_index=393,card_sets=[398]","I''m a bitch, I''m a lover, I''m a child, I''m ____."),
("bc_index=394,card_sets=[398]","Tonight on SNICK: Are You Afraid of ____?"),
("bc_index=395,card_sets=[406]","After blacking out during New Year''s Eve, I was awoken by ____."),
("bc_index=396,card_sets=[406]","What keeps me warm during the cold, cold winter?"),
("bc_index=397,card_sets=[406]","Wake up, America. Christmas is under attack by secular liberals and their ____."),
("bc_index=398,card_sets=[406]","Every Christmas, my uncle gets drunk and tells the story about ____."),
("bc_index=399,card_sets=[406,478]","Jesus is ____."),
("bc_index=400,card_sets=[406,478]","This holiday season, Tim Allen must overcome his fear of ____ to save Christmas."),
("bc_index=401,card_sets=[406]","On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and ____."),
("bc_index=402,card_sets=[414]","When you go to the polls on Tuesday, remember: a vote for me is a vote for ____."),
("bc_index=403,card_sets=[414]","Senator, I trust you enjoyed ____ last night. Now, can I count on your vote?"),
("bc_index=404,card_sets=[417]","Trump's great! Trump's got ____. I love that."),
("bc_index=405,card_sets=[417]","It's 3 AM. The red phone rings. It's ____. Who do you want answering?"),
("bc_index=406,card_sets=[417]","According to Arizona's stand-your-ground law, you're allowed to shoot someone if they're ____."),
("bc_index=407,card_sets=[421]","I can't believe Netflix is using ____ to promote <i>House of Cards.</i>"),
("bc_index=408,card_sets=[421]","A wise man said, Everything is about sex. Except sex. Sex is about ____."),
("bc_index=409,card_sets=[421]","I'm not going to lie. I despise ____. There, I said it."),
("bc_index=411,card_sets=[421]","We're not like other news organizations. Here at Slugline, we welcome ____ in the office."),
("bc_index=413,card_sets=[421]","Cancel all my meetings. We've got a situation with ____ that requires my immediate attention."),
("bc_index=414,card_sets=[421]","Our relationship is strictly professional. Let's not complicate things with ____."),
("bc_index=415,card_sets=[430]","My memory of last night is pretty hazy. I remember ____ and that's pretty much it."),
("bc_index=416,card_sets=[430]","Pledges! Time to prove you're Delta Phi material. Chug this beer, take off your shirts, and get ready for ____."),
("bc_index=417,card_sets=[430]","All classes today are canceled due to ____."),
("bc_index=418,card_sets=[430]","Did you know? Our college was recently named the #1 school for ____!"),
("bc_index=419,card_sets=[430]","The Department of Psychology is looking for paid research volunteers. Are you 18-25 and suffering from ____?"),
("bc_index=420,card_sets=[430]","In this paper, I will explore ____ from a feminist perspective."),
("bc_index=421,card_sets=[437]","Because they are forbidden from masturbating, Mormons channel their repressed sexual energy into ____."),
("bc_index=422,card_sets=[437]","Revealed: Why He Really Resigned! Pope Benedict's Secret Struggle with ____!"),
("bc_index=423,card_sets=[437,478]","Blessed are you, Lord our God, creator of the universe, who has granted us ____."),
("bc_index=424,card_sets=[437]","Kids these days with their iPods and their internet. In my day, we all needed to pass the time was ____."),
("bc_index=425,card_sets=[437]","GREETINGS<br>HUMANS<br><br>I AM ____ BOT<br><br>EXECUTING PROGRAM"),
("bc_index=428,card_sets=[437,478]","What's the one thing that makes an elf instantly ejaculate?"),
("bc_index=429,card_sets=[437]","I really hope my grandma doesn't ask me to explain ____ again."),
("bc_index=431,card_sets=[447]","Your father was a powerful wizard, Harry. Before he died, he left you something very precious: ____."),
("bc_index=432,card_sets=[447]","Having tired of poetry and music, the immortal elves now fill their days with ____."),
("bc_index=433,card_sets=[447]","And in the end, the dragon was not evil; he just wanted ____."),
("bc_index=434,card_sets=[447]","Who blasphemes and bubbles at the center of all infinity, whose name no lips dare speak aloud, and who gnaws hungrily in inconceivable, unlighted chambers beyond time?"),
("bc_index=435,card_sets=[447]","Legend tells of a princess who has been asleep for a thousand years and can only be awoken by ____."),
("bc_index=436,card_sets=[454]","Coming this spring from BioWare, <i>Mass Effect: ____.</i>"),
("bc_index=437,card_sets=[454]","I'm Commander Shepard, and this is my favorite place for ____ on the Citadel."),
("bc_index=438,card_sets=[454]","It turns out The Reapers didn't want to destroy the galaxy. They just wanted ____."),
("bc_index=439,card_sets=[454]","We were the best hand-to-hand combatants on the ship. I had reach, but she had ____."),
("bc_index=440,card_sets=[459]","Behold the Four Horsemen of the Apocalypse! War, Famine, Death, and ____."),
("bc_index=441,card_sets=[459]","Honey, Mommy and Daddy love you very much.But apparently Mommy loves ____ more than she loves Daddy."),
("bc_index=443,card_sets=[459]","Dear Mom and Dad, Camp is fun. I like capture the flag. Yesterday, one of the older kids taught me about ____. I love you, Casey"),
("bc_index=445,card_sets=[459]","Why am I so tired?"),
("bc_index=446,card_sets=[466]","Curiosity was put into safe mode after its hazcams detected ____."),
("bc_index=447,card_sets=[466]","NASA will spend 15 billion dollars on an unprecedented mission: ____ in space."),
("bc_index=448,card_sets=[469]","It's not delivery. It's ____."),
("bc_index=449,card_sets=[469]","Don't miss Rachel Ray's hit new show, <i>Cooking with ____.</i>"),
("bc_index=450,card_sets=[469]","I'm Bobby Flay, and if you can't stand ____, get out of the kitchen!"),
("bc_index=451,card_sets=[469]","Now on Netflix: <i>Jiro Dreams of ____.</i>"),
("bc_index=452,card_sets=[469]","Aw babe, your burps smell like ____!"),
("bc_index=453,card_sets=[469]","Excuse me, waiter. Could you take this back? This soup tastes like ____."),
("bc_index=454,card_sets=[476]","You have been waylaid by ____ and must defend yourself."),
("bc_index=455,card_sets=[476]","I have an idea even better than Kickstarter, and it's called ____starter."),
("bc_index=456,card_sets=[478]","Donna, pick up my dry cleaning and get my wife something for christmas. I think she likes ____."),
("bc_index=457,card_sets=[478]","It's beginning to look a lot like ____."),
("bc_index=458,card_sets=[482]","In the final round of this year's Omegathon, Omeganauts must face off in a game of ____."),
("bc_index=459,card_sets=[482]","Action stations! Action stations! Set condition one throughout the fleet and brace for ____!"),
("bc_index=460,card_sets=[487,485]","Press &darr;&darr;&larr;&rarr;B to unleash ____."),
("bc_index=461,card_sets=[485]","I don't know exactly how I got the PAX plague, but I suspect it had something to do with ____."),
("bc_index=463,card_sets=[487,505]","____: Achievement unlocked."),
("bc_index=464,card_sets=[487,494]","<i>(Heavy breathing)</i> Luke, I am ____."),
("bc_index=465,card_sets=[487,505]","What's the latest bullshit that's troubling this quaint fantasy town?"),
("bc_index=466,card_sets=[487,505]","What made Spock cry?"),
("bc_index=467,card_sets=[494]","What the hell?! They added a 6/6 with flying, trample, and ____."),
("bc_index=469,card_sets=[494]","Unfortunately, Neo, no one can be <i>told</i> what ____ is. You have to see it for yourself."),
("bc_index=470,card_sets=[494]","You think you have defeated me? Well, let's see how you handle ____!"),
("bc_index=471,card_sets=[499]","What's so important right now that you can't call your mother?"),
("bc_index=472,card_sets=[499]","According to Freud, all children progress through three stages of development: the oral stage, the anal stage, and the ____ stage."),
("bc_index=473,card_sets=[499]","Oh, your daughter should meet my son! He gives to charity, he loves ____ and did I mention he's a doctor?"),
("bc_index=474,card_sets=[499]","Coming to Broadway next season: ____ on the Roof."),
("bc_index=475,card_sets=[499]","Can't you see? The Jews are behind everything--the banks, the media, even ____!"),
("bc_index=476,card_sets=[505]","In the new DLC for Mass Effect, Shepard must save the galaxy from ____."),
("bc_index=477,card_sets=[505]","The most controversial game at PAX this year is an 8-bit indie platformer about ____."),
("bc_index=478,card_sets=[505]","There was a riot at the Gearbox panel when they gave the attendees ____."),
("bc_index=479,card_sets=[505]","No Enforcer wants to manage the panel on ____."),
("bc_index=480,card_sets=[510]","What gets me wet?"),
("bc_index=481,card_sets=[510]","My body, my voice! ____, my choice!"),
("bc_index=482,card_sets=[510]","My vagina's angry. My vagina's furious and it needs to talk. It needs to talk about ____."),
("bc_index=483,card_sets=[510]","Can a woman really have it all? A career <i>and ____?</i>"),
("bc_index=484,card_sets=[510]","Tampax&reg;: Don't let your period ruin ____."),
("bc_index=485,card_sets=[510]","New from Mattel, it's ____ Barbie!"),
("bc_index=486,card_sets=[517]","Donald Trump's first act as president was to outlaw ____."),
("bc_index=487,card_sets=[517]","Donald Trump has nominated ____ for his VP."),
("bc_index=488,card_sets=[517]","In 2019, Donald Trump eliminated our national parks to make room for ____."),
("bc_index=490,card_sets=[521]","From WBEZ Chicago, it's <i>This American Life.</i> Today on our program, ____. Stay with us."),
("bc_index=491,card_sets=[521]","My name is Inigo Montoya. You killed my father. Prepare for ____."),
("bc_index=492,card_sets=[521]","[rorschach test] What do you see?"),
("bc_index=493,card_sets=[521]","Sir, we found you passed out naked on the side of the road. What's the last thing you remember?"),
("bc_index=494,card_sets=[521]","You can't wait forever. It's time to talk to your doctor about ____."),
("bc_index=495,card_sets=[521]","The elders of the Ibo tribe of Nigeria recommend ____ as a cure for impotence."),
("bc_index=496,card_sets=[521]","The Westboro Baptist Church is now picketing soldiers' funerals with signs that read 'GOD HATES ____!'"),
("bc_index=497,card_sets=[530]","Looking to earn big bucks? Learn how to make ____ work for you!"),
("bc_index=498,card_sets=[530]","How are the writers of Cards Against Humanity spending your $25?"),
("bc_index=499,card_sets=[533]","Fear leads to anger. Anger leads to hate. Hate leads to ____."),
("bc_index=500,card_sets=[533]","Computer! Display ____ on screen. Enhance."),
("bc_index=501,card_sets=[533]","You're not going to believe this, but I'm you from the future! You've got to stop ____."),
("bc_index=502,card_sets=[533]","This won't be like negotiating with the Vogons. Humans only respond to one thing: ____."),
("bc_index=503,card_sets=[533]","Madam President, the asteroid is headed directly for Earth and there's one one thing that can stop it: ____."),
("bc_index=504,card_sets=[533]","You have violated the Prime Directive! You exposed an alien culture to ____ before they were ready."),
("bc_index=505,card_sets=[533]","What is the answer to life, the universe, and everything?"),
("bc_index=506,card_sets=[541]","Why did the chicken cross the road?"),
("bc_index=507,card_sets=[541]","Some men aren't looking for anything logical, like money. They can't be bought, bullied, reasoned, or negotiated with. Some men just want ____."),
("bc_index=508,card_sets=[541]","America is hungry. America needs ____."),
("bc_index=509,card_sets=[541]","In bourgeois society, capital is independent and has individuality, while the living person is ____."),
("bc_index=510,card_sets=[541]","Housekeeping! You want ____?"),
("bc_index=511,card_sets=[541]","BowWOW! is the first pet hotel in LA that offers ____ for dogs."),
("bc_index=512,card_sets=[541]","Astronomers have discovered that the universe consists of 5% ordinary matter, 25% dark matter, and 70% ____."),
("bc_index=513,card_sets=[541]","Hey, whatever happened to Renee Zellweger?"),
("bc_index=514,card_sets=[541]","What's wrong with these gorillas?"),
("bc_index=515,card_sets=[541]","You say tomato, I say ____."),
("bc_index=516,card_sets=[552]","A study published in <i>Nature</i> this week found that ____ is good for you in small doses."),
("bc_index=517,card_sets=[552]","What really killed the dinosaurs?"),
("bc_index=520,card_sets=[552]","In what's being hailed as a major breakthrough, scientists have synthesized ____ in the lab."),
("bc_index=521,card_sets=[552]","Hey there, Young Scientists! Put on your labcoats and strap on your safety goggles, because today we're learning about ____!"),
("bc_index=523,card_sets=[560]","Hold up. I gotta deal with ____, then I'mma smoke this."),
("bc_index=524,card_sets=[560]","Okay here's the pitch. James Franco and Seth Rogen are trying to score some weed, and then ____ happens."),
("bc_index=525,card_sets=[560]","You know what's like, really funny when you think about it? ____."),
("bc_index=526,card_sets=[560]","Instead of playing a card this round, everyone must stare at the Card Czar while making a sound you'd make after tasting something delicious."),
("bc_index=527,card_sets=[560]","Everyone is staring at you because you're ____."),
("bc_index=528,card_sets=[566]","Wait, I came here to buy socks. How did I wind up with ____?"),
("bc_index=529,card_sets=[568]","Hey, you guys want to try this awesome new game? It's called ____."),
("bc_index=530,card_sets=[568]","For my turn, I will spend four gold and allocate all three workers to ____."),
("bc_index=531,card_sets=[568]","Backers who supported Tabletop at the $25,000 level were astonished to receive ____ from Wil Wheaton himself."),
("bc_index=532,card_sets=[572]","I'm just gonna stay in tonight. You know, Netflix and ____."),
("bc_index=533,card_sets=[572]","What did I nickname my genitals?"),
("bc_index=534,card_sets=[572]","This app is basically Tinder, but for ____."),
("bc_index=535,card_sets=[572]","You guys, you can buy ____ on the dark web."),
("bc_index=536,card_sets=[572]","Don't worry, Penny! Go Go Gadget ____!"),
("bc_index=537,card_sets=[572]","TRIGGER WARNING: ____."),
("bc_index=540,card_sets=[572]","Nothing says ""I love you"" like ____.");
